### ISSUE TITLE
Domain Information Model

### ISSUE THREAD

**Issue by krausma-4** [CalamariFritti/WebApp2020#1]
Hello you both,

we created the DIM with your given information.  Please have a look and tell us if we have missunderstood something.

We also have a question: You mentioned that it should be possible to create a user profil for "concert manager". Does it mean you want to have different roles for the entity "user"?

Best regards.

<img width="394" alt="DIM" src="https://user-images.githubusercontent.com/59192219/84128283-aa4ca500-aa40-11ea-9e21-b89775f08fe5.png">

**Comment by CalamariFritti** [comment]
Hello back,

and thank you for your model. This already looks very good. 
There is no need for an extra role: "concert manager", because the purpose of creating an account is to set up events at the club, so the regular users are the 'concert managers'. But there has to be a distinction between regular users and admin users. Although it is probably not necessary to establish roles for this.

What should be possible is that a user can not only create an event, but can also create a new entry for the artists database. Is this already covered in the model?

**Comment by krausma-4** [comment]
Ok here is a revised version of the DIM. The creation of an artist from a user wasn't covered. We didn't put a cardinality to this association because we think its not important to know who is the creator of an artist, right?

<img width="394" alt="DIM" src="https://user-images.githubusercontent.com/59192219/84154905-f7903d00-aa67-11ea-8260-4c1f361c8282.png">

**Comment by CalamariFritti** [comment]
Ok, perfect. 

As you thought, it is not important to know which user created an artist. 
Looks good to me.
